version: '3'

services:

  cvk:
    image: cvk:0.0.1
    build:
      context: cvk
      dockerfile: Dockerfile
    environment:
      PORT: 6745
    ports:
      - "6745:6745"
    volumes:
      - ./cvk:/home/cvk
    working_dir: /home/cvk
    command: uvicorn --host 0.0.0.0 --port 6745 --reload cvk.main:app
