version: '3'

services:

  cvk:
    image: cvk:0.0.1
    build:
      context: cvk
      dockerfile: Dockerfile
    environment:
      PORT: 6745
      POLL_STATION_URL: "https://www.drv.gov.ua/portal/cm?option=ext_dvk&pid100=46&pf3001=372&prejim=2"
      CONSTITUENSIES_URL: "https://www.cvk.gov.ua/pls/vm2020/pvm116pt001f01=695pt00_t001f01=695pid112=2pid100=46pid102=3634rej=0.html#"
      CANDIDATES_URL: "https://www.cvk.gov.ua/pls/vm2020/pvm056pid102=63610pf7691=63610pt001f01=695rej=0pt00_t001f01=695.html#89a"
    ports:
      - "6745:6745"
    volumes:
      - ./cvk:/home/cvk
    working_dir: /home/cvk
    command: uvicorn --host 0.0.0.0 --port 6745 --reload cvk.main:app

  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
